import type { Tour } from "nextstepjs";

export const MAIN_TOUR = "main";
export const ONBOARDING_STORAGE_KEY = "hubride:onboarding:v1";

export const mainTour: Tour[] = [
  {
    tour: MAIN_TOUR,
    steps: [
      {
        icon: null,
        title: "Welcome to Hub-Ride",
        content: "This quick guide walks through the demo flow: create a room, find riders, dispatch, and view bookings.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 16,
      },
      {
        icon: null,
        title: "Pick a demo user",
        content: "Switch between seeded demo users. The selected user controls room creation, joining, and booking history.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: null,
        title: "Check the demo wallet",
        content: "Wallet balance is shown for the current demo user and supports the pre-pay story in the pitch.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 999,
      },
      {
        icon: null,
        title: "Create a ride room",
        content: "Start from the create room flow, choose origin and destination hubs, then let the backend calculate distance and H3 cells.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
        nextRoute: "/rooms/new",
      },
      {
        icon: null,
        title: "Choose the origin",
        content: "Search from the seeded address list. The selected place sends latitude and longitude to the backend.",
        selector: "#tour-origin-input",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: null,
        title: "Choose the destination",
        content: "The route preview blocks short trips under two kilometers and helps explain the hub-based model.",
        selector: "#tour-destination-input",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
        nextRoute: "/rooms/browse",
        prevRoute: "/rooms/new",
      },
      {
        icon: null,
        title: "Browse matching rooms",
        content: "Joiners search the same route and see rooms found through the backend H3 matching service.",
        selector: "#tour-browse-rooms",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 16,
        prevRoute: "/rooms/new",
      },
      {
        icon: null,
        title: "Watch the countdown",
        content: "On a room detail page, this timer drives the dispatch moment. It appears after a host creates a room or a joiner enters one.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 16,
      },
      {
        icon: null,
        title: "Track room members",
        content: "The member list updates as riders join or leave, using the room topic subscription and cache reconciliation.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 16,
      },
      {
        icon: null,
        title: "Compare dispatch quotes",
        content: "After dispatch, the room shows partner quotes and highlights the best fare before each rider lands on booking confirmation.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 16,
        nextRoute: "/bookings",
      },
      {
        icon: null,
        title: "Review bookings",
        content: "After dispatch, confirmed bookings appear here for the current demo user.",
        selector: "#tour-bookings",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 16,
        prevRoute: "/rooms/browse",
      },
    ],
  },
];
